### ISSUE TITLE
error response recieved from upstream api

### ISSUE THREAD

**Issue by sargon2** [piquette/finance-go#26]
I'm getting `error response recieved from upstream api` on all requests.  In the log, it says `{"code":"Unauthorized","description":"Invalid Cookie"}`.

**Comment by sargon2** [comment]
Today it seems to be working again.

**Comment by valankar** [comment]
Perhaps reopen this bug.

**Comment by psanford** [comment]
Changing the yahoo api url from `v7` to `v6` should give you something that works right now. There's a PR for that here: #27

**Comment by sargon2** [comment]
I don't have permission to reopen the bug.

**Comment by kfwalther** [comment]
Thanks @psanford, ran `go get github.com/piquette/finance-go@latest` to grab the latest version (v1.1.0) to include the PR, and it fixed the issue!

**Comment by KasperKornak** [comment]
Guys, PR opened by @alai04 from last month fixed it for a while. However, about three days ago I've noticed that `error response from upstream api` occurred again and after looking through [this issue](https://github.com/dpguthrie/yahooquery/issues/178) i tried to access url mentioned and got the following response:

```json
{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback"}}}
```
So after heading to the link, they basically say that they can't redistribute financial data from 3rd parties in API form.

**Comment by sargon2** [comment]
I switched to this mirror and it seems to be working, at least for now: https://github.com/psanford/finance-go

**Comment by kfwalther** [comment]
I also began seeing the Unauthorized errors again, even after switching to v1.1.0. Looks like the fork might be the way to go for now.

**Comment by sahilsk11** [comment]
Bumping this, as I received the same error on v1.1.0 when I run:

```
q, err := equity.Get("AAPL")
if err != nil {
  // Uh-oh.  
  panic(err)
}

// Success!
fmt.Println(q)
```
